export interface Language {
  code: string;
  name: string;
  nativeName: string;
}

export const Languages: Language[] = [
  {code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans'},
  // {code: 'am', name: 'Amharic', nativeName: 'አማርኛ'},
  {code: 'ar', name: 'Arabic', nativeName: 'العربية'},
  {code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
  // {code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
  {code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan'},
  {code: 'be', name: 'Belarusian', nativeName: 'Беларуская'},
  {code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
  // {code: 'bs', name: 'Bosnian', nativeName: 'Bosanski'},
  // {code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
  {code: 'ca', name: 'Catalan', nativeName: 'Català'},
  {code: 'zh', name: 'Chinese', nativeName: '中文'},
  // {code: 'hr', name: 'Croatian', nativeName: 'Hrvatski'},
  {code: 'cs', name: 'Czech', nativeName: 'Česky'},
  {code: 'da', name: 'Danish', nativeName: 'Dansk'},
  {code: 'nl', name: 'Dutch', nativeName: 'Nederlands'},
  {code: 'en', name: 'English', nativeName: 'English'},
  {code: 'et', name: 'Estonian', nativeName: 'Uesti'},
  {code: 'fi', name: 'Finnish', nativeName: 'Suomi'},
  {code: 'fr', name: 'French', nativeName: 'Française'},
  {code: 'gl', name: 'Galician', nativeName: 'Galego'},
  // {code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
  {code: 'de', name: 'German', nativeName: 'Deutsch'},
  {code: 'el', name: 'Greek', nativeName: 'Ελληνικά'},
  // {code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
  // {code: 'ha', name: 'Hausa', nativeName: 'هَوُسَ'},
  {code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'},
  {code: 'hu', name: 'Hungarian', nativeName: 'Magyar'},
  {code: 'id', name: 'Indonesian', nativeName: 'Bahasa'},
  // {code: 'is', name: 'Icelandic', nativeName: 'Íslenska'},
  {code: 'it', name: 'Italian', nativeName: 'Italiano'},
  {code: 'ja', name: 'Japanese', nativeName: '日本語'},
  // {code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
  {code: 'kk', name: 'Kazakh', nativeName: 'Қазақ'},
  // {code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ'},
  {code: 'ko', name: 'Korean', nativeName: '한국어'},
  // {code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch'},
  // {code: 'ln', name: 'Lingala', nativeName: 'Lingála'},
  // {code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
  {code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių'},
  {code: 'lv', name: 'Latvian', nativeName: 'Latviešu'},
  {code: 'mk', name: 'Macedonian', nativeName: 'Македонски'},
  // {code: 'ms', name: 'Malay', nativeName: 'Melayu'},
  // {code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
  // {code: 'mt', name: 'Maltese', nativeName: 'Malti'},
  // {code: 'mi', name: 'Māori', nativeName: 'Māori'},
  {code: 'mr', name: 'Marathi', nativeName: 'मराठी'},
  // {code: 'mn', name: 'Mongolian', nativeName: 'Монгол'},
  // {code: 'nb', name: 'Norwegian', nativeName: 'Norsk'},
  {code: 'ne', name: 'Nepali', nativeName: 'नेपाली'},
  // {code: 'ng', name: 'Ndonga', nativeName: 'Owambo'},
  // {code: 'no', name: 'Norwegian', nativeName: 'Norsk'},
  // {code: 'pa', name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ'},
  {code: 'fa', name: 'Persian', nativeName: 'فارسی'},
  {code: 'pl', name: 'Polish', nativeName: 'Polski'},
  {code: 'pt', name: 'Portuguese', nativeName: 'Português'},
  {code: 'ro', name: 'Romanian', nativeName: 'Română'},
  {code: 'ru', name: 'Russian', nativeName: 'Русский'},
  // {code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी'},
  {code: 'sr', name: 'Serbian', nativeName: 'Српски'},
  {code: 'sk', name: 'Slovak', nativeName: 'Slovenčina'},
  {code: 'sl', name: 'Slovene', nativeName: 'Slovenščina'},
  // {code: 'so', name: 'Somali', nativeName: 'Soomaaliga'},
  {code: 'es', name: 'Spanish', nativeName: 'Español'},
  {code: 'sv', name: 'Swedish', nativeName: 'Svenska'},
  {code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
  // {code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ'},
  {code: 'th', name: 'Thai', nativeName: 'ไทย'},
  // {code: 'tl', name: 'Tagalog', nativeName: 'Tagalog᜔'},
  {code: 'tr', name: 'Turkish', nativeName: 'Türkçe'},
  {code: 'uk', name: 'Ukrainian', nativeName: 'Українська'},
  {code: 'ur', name: 'Urdu', nativeName: 'اردو'},
  // {code: 'uz', name: 'Uzbek', nativeName: 'Ўзбек'},
  {code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt'},
  {code: 'cy', name: 'Welsh', nativeName: 'Cymraeg'}
];

export const languagesList = Languages.map((team: Language) => {
  return {
    value: team.code,
    text: team.name,
  };
});
